### ISSUE TITLE
Adicionar a moeda usada.

### ISSUE THREAD

**Issue by leogabrielps** [estevaofay/stock-quote-service#9]
Seria adicionar qual a moeda está sendo usada para determina o preço de uma ação, exemplo com **uma ação BR:**
```json
[{
    "provider": "Yahoo",
    "ticker": "RAIZ4.SA",
    "currency": "BRL",
    "price": 3.91
  }]
```

Uma ação do **Estados Unidos**:
```json
[{
    "provider": "Yahoo",
    "ticker": "AAPL",
    "currency": "USD",
    "price": 150.72
  }]
```

Dentro do yfinance, para pegar o tipo de Currency usado pela a ação fica na tag **financialCurrency**

**Comment by estevaofay** [comment]
@leogabrielps Pô, sensacional a sugestão!

Bora fazer isso com certeza. 

Fica o convite para você abrir o PR, do contrário eu posso abrir e escrever sobre

**Comment by leogabrielps** [comment]
@estevaofay consegui fazer de boa na da Yahoo, já que nem precisou chamar outra classe etc, mas, na AlphaVantage, notei dois problema: 
1. Na classe utilizada por você não vem a informação que vem a moeda utilizada pela empresa, por isso tive que usar uma outra classe que tinha.
2. Nessa segunda classe fiz os testeis com as Stocks inglesas e funcionou perfeitamente, porém, quando eu fui testar com Stocks de outros países começou a dar BO, porque a AlphaVantage só tem o Overview das empresas do USA, não é igual a da Yahoo que tem de todo o mundo.

**No Pull Requests que eu fiz ele só está aceitando Stocks do USA, se você tiver alguma ideia do que pode ser feito,**

**Comment by estevaofay** [comment]
@leogabrielps mergeado!

Fechando a issue
